// components-demo/react-demo/src/demo-components/UsageFull.tsx
import React from 'react';
import { Icon } from '@iconizza/react';

export function FullUsageDemo() {
	return (
		<section className="icon-24">
			<h1>Usage (full module)</h1>
			<div>
				Icons referenced by name (as SVG, as SPAN):{' '}
				<Icon icon="mdi:home" /> <Icon icon="mdi:home" mode="style" />
			</div>
			<div className="alert">
				<Icon icon="mdi-light:alert" />
				Important notice with alert icon!
			</div>
		</section>
	);
}

// components-demo/svelte-demo/src/demo-components/UsageFull.svelte
<script>
	import Icon from '@iconizza/svelte';

    let onLoadCalled = false;
</script>

<section class="icon-24">
    <h1>Usage  (full module)</h1>
    <div>
        Icon referenced by name (as svg, as span): <Icon icon="mdi:home" mode="svg" /><Icon icon="mdi:home" mode="style" />
    </div>
    <div class="alert">
        <Icon icon="mdi-light:alert" on:load={event => {
            console.log(event);
            onLoadCalled = true;
        }} mode="style" />
        Important notice with alert icon{onLoadCalled ? '' : ' (loading...)'}!
    </div>
</section>
