// components-demo/vue-demo/src/demo-components/UsageFull.vue
<template>
	<section class="icon-24">
		<h1>Usage (full module)</h1>
		<div>
			Icons referenced by name (rendered as SVG, then as SPAN):
			<Icon icon="mdi:home" />
			<Icon icon="mdi:home" mode="style" />
		</div>
		<div class="alert">
			<Icon icon="mdi-light:alert" />Important notice with alert icon!
		</div>
	</section>
</template>

<script lang="ts">
import { Icon } from '@iconizza/vue';

export default {
	components: {
		Icon,
	},
};
</script>

// components-demo/react-demo/src/demo-components/UsageFull.tsx
import React from 'react';
import { Icon } from '@iconizza/react';

export function FullUsageDemo() {
	return (
		<section className="icon-24">
			<h1>Usage (full module)</h1>
			<div>
				Icons referenced by name (as SVG, as SPAN):{' '}
				<Icon icon="mdi:home" /> <Icon icon="mdi:home" mode="style" />
			</div>
			<div className="alert">
				<Icon icon="mdi-light:alert" />
				Important notice with alert icon!
			</div>
		</section>
	);
}
